# Generated by Django 3.0.4 on 2020-04-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mpolynom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpolynomyal', models.CharField(max_length=1000, verbose_name='M-polynomial')),
                ('structure_name', models.CharField(max_length=200, unique=True)),
                ('keywords', models.CharField(max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('links', models.TextField(blank=True)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
