# Generated by Django 3.0.4 on 2020-05-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpolynom',
            options={'verbose_name': 'M-polynomial'},
        ),
    ]
