# Generated by Django 3.0.4 on 2020-04-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpolynom',
            name='structure_picture',
        ),
    ]
