# Generated by Django 3.0.4 on 2020-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_mpolynom_structure_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpolynom',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mpolynom',
            name='links',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mpolynom',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mpolynom',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mpolynom',
            name='structure_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
