# Generated by Django 3.0.4 on 2020-08-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200829_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpolynom',
            name='status',
            field=models.CharField(choices=[('w', 'waiting'), ('a', 'approved'), ('d', 'disapproved')], default='waiting', max_length=15),
        ),
    ]
