# Generated by Django 3.0.4 on 2020-10-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200829_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('search.mpolynom',),
        ),
        migrations.AddField(
            model_name='mpolynom',
            name='new_comments',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='mpolynom',
            name='new_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='mpolynom',
            name='new_links',
            field=models.TextField(blank=True, verbose_name='links'),
        ),
        migrations.AddField(
            model_name='mpolynom',
            name='new_references',
            field=models.TextField(blank=True, verbose_name='references'),
        ),
        migrations.AlterField(
            model_name='mpolynom',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mpolynom',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved'), ('disapproved', 'disapproved'), ('new_comments', 'new_comments')], default='waiting', max_length=15),
        ),
    ]
