# Generated by Django 3.0.4 on 2020-10-16 15:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import search.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0009_auto_20201010_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMpolynom',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mpolynomyal', models.CharField(max_length=1000, verbose_name='M-polynomial')),
                ('structure_name', models.CharField(db_index=True, max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('links', models.TextField(blank=True)),
                ('author', models.CharField(default=django.contrib.auth.models.User, editable=False, max_length=100)),
                ('publication_date', models.DateField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved'), ('disapproved', 'disapproved'), ('new_comments', 'new_comments')], default='waiting', max_length=15)),
                ('new_keywords', models.CharField(blank=True, max_length=200)),
                ('new_comments', models.TextField(blank=True)),
                ('new_references', models.TextField(blank=True)),
                ('new_links', models.TextField(blank=True)),
                ('new_comments_authors', models.CharField(blank=True, max_length=5000)),
                ('Mid', models.CharField(default=search.models.unique_rand, editable=False, max_length=10, verbose_name='id')),
                ('nb_tokens', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical M-polynomial',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mpolynomyal', models.CharField(max_length=1000, verbose_name='M-polynomial')),
                ('structure_name', models.CharField(db_index=True, max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('links', models.TextField(blank=True)),
                ('author', models.CharField(default=django.contrib.auth.models.User, editable=False, max_length=100)),
                ('publication_date', models.DateField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved'), ('disapproved', 'disapproved'), ('new_comments', 'new_comments')], default='waiting', max_length=15)),
                ('new_keywords', models.CharField(blank=True, max_length=200)),
                ('new_comments', models.TextField(blank=True)),
                ('new_references', models.TextField(blank=True)),
                ('new_links', models.TextField(blank=True)),
                ('new_comments_authors', models.CharField(blank=True, max_length=5000)),
                ('Mid', models.CharField(default=search.models.unique_rand, editable=False, max_length=10, verbose_name='id')),
                ('nb_tokens', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
