# Generated by Django 3.0.4 on 2020-10-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_historicalcomment_historicalmpolynom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalcomment',
            old_name='mpolynomyal',
            new_name='mpolynomial',
        ),
        migrations.RenameField(
            model_name='historicalmpolynom',
            old_name='mpolynomyal',
            new_name='mpolynomial',
        ),
        migrations.RenameField(
            model_name='mpolynom',
            old_name='mpolynomyal',
            new_name='mpolynomial',
        ),
    ]
