# Generated by Django 3.0.4 on 2020-10-30 15:23

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20201030_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcomment',
            name='author_username',
            field=models.CharField(default=django.contrib.auth.models.User, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalmpolynom',
            name='author_username',
            field=models.CharField(default=django.contrib.auth.models.User, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='mpolynom',
            name='author_username',
            field=models.CharField(default=django.contrib.auth.models.User, editable=False, max_length=100),
        ),
    ]
