# Generated by Django 3.0.4 on 2020-12-04 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_auto_20201030_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcomment',
            name='mpolynomial_see',
            field=models.CharField(default='stara', max_length=1000, verbose_name='M-polynomial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmpolynom',
            name='mpolynomial_see',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='M-polynomial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpolynom',
            name='mpolynomial_see',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='M-polynomial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='mpolynomial',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalmpolynom',
            name='mpolynomial',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mpolynom',
            name='mpolynomial',
            field=models.CharField(max_length=1000),
        ),
    ]
