# Generated by Django 3.0.4 on 2020-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20201204_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcomment',
            name='mpolynomial',
            field=models.CharField(default='test', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalmpolynom',
            name='mpolynomial',
            field=models.CharField(default='test', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mpolynom',
            name='mpolynomial',
            field=models.CharField(default='test', max_length=1000),
        ),
    ]
