# Generated by Django 4.1 on 2022-09-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_auto_20201204_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcomment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical comment', 'verbose_name_plural': 'historical comments'},
        ),
        migrations.AlterModelOptions(
            name='historicalmpolynom',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical M-polynomial', 'verbose_name_plural': 'historical M-polynomials'},
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmpolynom',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
